### PR TITLE
Add two resources to resources page

### PR DESCRIPTION
**Pull request by stevensona**
Disclaimer: Brisk Forms is a service that I created. However I believe it fits on this list because it provides the same functionality as other services with no cost.

Firebase Hosting is a resource I have used as a way to get static sites online with a custom domain name at no cost. While the free tier has bandwidth limits imposed, I presume it sufficient for majority of users with the added benefit that there are no restrictions on advertising.

### CODE REVIEW

**Comment by daveaglick** [comment]
:+1: Thanks a lot for this! I'd be happy to add them - I'm actually out of town right now, so I'll get this merged later this week or next.

**Comment by daveaglick** [comment]
Thanks - this has been merged and will go live on the next publish soon. I've got a new version coming out soon, so I'll probably do a publish then. If not, I'll get a interim version out next week.

**Comment by stevensona** [comment]
Sounds good. Welcome back. Not sure about you, but for me, it always feels good to get back into code after a break.

**Comment by daveaglick** [comment]
:smile: As is typical for a long break, I'm having a little trouble remembering how to computer at the moment...

**Pull request merged**
